from testMongoGen_DaoMaster import DaoMaster
from CatalogItemType import CatalogItemType

if __name__ == "__main__":
    dao_master = DaoMaster()
    dao_session = dao_master.getSession()
    catalog_item_type_dao = dao_session.getCatalogItemTypeDao()

    catalog_item_type = CatalogItemType()
    catalog_item_type.setId(0)
    catalog_item_type.setItemType('SRC')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(1)
    catalog_item_type.setItemType('PRO')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(2)
    catalog_item_type.setItemType('ENV')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(3)
    catalog_item_type.setItemType('CHR')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(4)
    catalog_item_type.setItemType('RIG')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(5)
    catalog_item_type.setItemType('FXS')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(6)
    catalog_item_type.setItemType('TEM')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(7)
    catalog_item_type.setItemType('GEO')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(8)
    catalog_item_type.setItemType('ART')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(9)
    catalog_item_type.setItemType('SHD')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(10)
    catalog_item_type.setItemType('TEX')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(11)
    catalog_item_type.setItemType('CCH')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(12)
    catalog_item_type.setItemType('SQI')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(13)
    catalog_item_type.setItemType('DCC')
    catalog_item_type_dao.create(catalog_item_type)
    catalog_item_type.setId(14)
    catalog_item_type.setItemType('NON')
    catalog_item_type_dao.create(catalog_item_type)

    # catalog_array = catalog_item_type_dao.readAll()
    # print(len(catalog_array))




